### ISSUE TITLE
Creating a Git repo causes errors

### ISSUE THREAD

**Issue by sagebind** [oh-my-fish/plugin-vcs#5]
Creating a new Git repository inside the current directory causes vcs to not function correctly until you change directories.

Example:

```fish
~ $ mkdir test
~ $ cd test
~/test $ git init
~/test $ vcs.root
fish: Unknown command 'vcs.root'
```

The errors are more intrusive if the current theme uses vcs to display info in the prompt.

**Comment by derekstavis** [comment]
Should be now fixed in 6d0cc9d
